/**
 * Editor authentication.
 *
 * The game itself is public. This guards the one thing that can actually cause
 * damage: writing level files to disk. Opening the editor UI is gated too, but
 * that gate is cosmetic by nature — the editor runs in the visitor's browser,
 * so anyone determined enough can reach it. What they cannot do is persist
 * anything, because every write goes through requireSession() below.
 *
 * Config comes from the environment (see .env.example); nothing secret is ever
 * compiled into the client bundle.
 *
 *   EDITOR_PASSWORD_SALT   hex, per-install, generated by scripts/set-editor-password.mjs
 *   EDITOR_PASSWORD_HASH   hex scrypt digest of the password
 *   SESSION_SECRET         hex, signs session cookies
 */

import { createHmac, randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';

export const COOKIE_NAME = 'jg_editor';
const SESSION_TTL_MS = 12 * 60 * 60 * 1000;

// scrypt cost. N=2^15 lands around 100ms per attempt on a small VPS, which is
// plenty against offline cracking and unnoticeable for a single interactive login.
// These params need 128*N*r = 32MiB, which is exactly Node's default maxmem
// ceiling, so maxmem has to be raised or scryptSync throws.
const SCRYPT = { N: 32768, r: 8, p: 1, keylen: 64, maxmem: 64 * 1024 * 1024 };

const MAX_ATTEMPTS = 5;
const LOCKOUT_MS = 15 * 60 * 1000;
const attempts = new Map();

export function deriveHash(password, saltHex) {
  const { keylen, ...opts } = SCRYPT;
  return scryptSync(password, Buffer.from(saltHex, 'hex'), keylen, opts).toString('hex');
}

export function generateSalt() {
  return randomBytes(32).toString('hex');
}

export function generateSecret() {
  return randomBytes(48).toString('hex');
}

/** True when the server has everything it needs to authenticate anyone. */
export function isConfigured() {
  return Boolean(
    process.env.EDITOR_PASSWORD_SALT &&
      process.env.EDITOR_PASSWORD_HASH &&
      process.env.SESSION_SECRET,
  );
}

/**
 * Constant-time password check. Returns false for every wrong password and for
 * every password at all when the server is unconfigured — an install that never
 * ran the setup script has no editor, rather than an editor with no password.
 */
export function verifyPassword(password) {
  if (!isConfigured()) return false;
  if (typeof password !== 'string' || password.length === 0 || password.length > 512) return false;
  const expected = Buffer.from(process.env.EDITOR_PASSWORD_HASH, 'hex');
  const actual = Buffer.from(deriveHash(password, process.env.EDITOR_PASSWORD_SALT), 'hex');
  if (expected.length !== actual.length) return false;
  return timingSafeEqual(expected, actual);
}

/** Per-IP throttle so the password cannot be ground down by brute force. */
export function rateLimit(ip) {
  const now = Date.now();
  const entry = attempts.get(ip);
  if (!entry || now - entry.first > LOCKOUT_MS) {
    attempts.set(ip, { count: 0, first: now });
    return { allowed: true, retryAfterSec: 0 };
  }
  if (entry.count >= MAX_ATTEMPTS) {
    return { allowed: false, retryAfterSec: Math.ceil((LOCKOUT_MS - (now - entry.first)) / 1000) };
  }
  return { allowed: true, retryAfterSec: 0 };
}

export function recordFailure(ip) {
  const entry = attempts.get(ip);
  if (entry) entry.count++;
}

export function clearFailures(ip) {
  attempts.delete(ip);
}

/** Drop throttle entries that have aged out, so the map cannot grow forever. */
export function sweepRateLimit() {
  const now = Date.now();
  for (const [ip, entry] of attempts) {
    if (now - entry.first > LOCKOUT_MS) attempts.delete(ip);
  }
}

function sign(payload) {
  return createHmac('sha256', process.env.SESSION_SECRET).update(payload).digest('base64url');
}

export function createSessionToken() {
  const payload = Buffer.from(JSON.stringify({ exp: Date.now() + SESSION_TTL_MS })).toString(
    'base64url',
  );
  return `${payload}.${sign(payload)}`;
}

export function verifySessionToken(token) {
  // No secret configured means no session can be valid. Without this guard a
  // leftover cookie from an earlier install makes createHmac throw on a null
  // key, and every request — including plain GETs — answers 500 instead of
  // simply reporting that nobody is logged in.
  if (!process.env.SESSION_SECRET) return false;
  if (!token || typeof token !== 'string') return false;
  const [payload, mac] = token.split('.');
  if (!payload || !mac) return false;

  const expectedMac = Buffer.from(sign(payload));
  const actualMac = Buffer.from(mac);
  if (expectedMac.length !== actualMac.length) return false;
  if (!timingSafeEqual(expectedMac, actualMac)) return false;

  try {
    const { exp } = JSON.parse(Buffer.from(payload, 'base64url').toString());
    return typeof exp === 'number' && Date.now() < exp;
  } catch {
    return false;
  }
}

export function readCookie(req, name) {
  const header = req.headers.cookie;
  if (!header) return null;
  for (const part of header.split(';')) {
    const eq = part.indexOf('=');
    if (eq < 0) continue;
    if (part.slice(0, eq).trim() === name) return decodeURIComponent(part.slice(eq + 1).trim());
  }
  return null;
}

export function sessionCookie(token) {
  // Secure is safe on http://localhost too — browsers treat localhost as a
  // trustworthy origin — so the flag needs no environment-specific escape hatch.
  const maxAge = Math.floor(SESSION_TTL_MS / 1000);
  return `${COOKIE_NAME}=${token}; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=${maxAge}`;
}

export function clearCookie() {
  return `${COOKIE_NAME}=; HttpOnly; Secure; SameSite=Strict; Path=/; Max-Age=0`;
}

export function hasSession(req) {
  return verifySessionToken(readCookie(req, COOKIE_NAME));
}
