/**
 * Game audio: generated samples, with the original synth kept as a fallback.
 *
 * The synth version of this file made a square-wave blip for the jump and
 * filtered noise for the landing. It worked, and it belonged to a different
 * game — a square wave in a photorealistic rainforest is the audio equivalent
 * of an untextured box. The samples are generated by scripts/gen-audio.mjs.
 *
 * The synth is still here and still wired up. Samples are fetched
 * asynchronously and can fail — offline, a bad deploy, a blocked request — and
 * a game that goes silent because a download failed is worse than one that
 * falls back to a beep. Whatever has loaded is used; whatever has not, is not.
 */

const BASE = '/assets/audio';

/** One-shot sample ids and their files. */
const SAMPLES = {
  ambience: 'ambience_jungle.mp3',
  step_a: 'step_stone_a.mp3',
  step_b: 'step_stone_b.mp3',
  step_c: 'step_stone_c.mp3',
  jump: 'jump_effort.mp3',
  land: 'land_thud.mp3',
  crumble: 'crumble_crack.mp3',
  bounce: 'bounce_spring.mp3',
} as const;

type SampleId = keyof typeof SAMPLES;

let ctx: AudioContext | null = null;
let master: GainNode | null = null;
let sfxBus: GainNode | null = null;
let ambienceBus: GainNode | null = null;
const buffers = new Map<SampleId, AudioBuffer>();
let loading = false;

function ensureCtx(): { ctx: AudioContext; master: GainNode } | null {
  if (ctx && master) return { ctx, master };
  try {
    ctx = new AudioContext();
    master = ctx.createGain();
    master.gain.value = 0.5;
    master.connect(ctx.destination);

    sfxBus = ctx.createGain();
    sfxBus.gain.value = 1;
    sfxBus.connect(master);

    // Ambience sits well under everything else. It is a bed: the moment you
    // notice it as a sound rather than as a place, it is too loud.
    ambienceBus = ctx.createGain();
    ambienceBus.gain.value = 0;
    ambienceBus.connect(master);

    return { ctx, master };
  } catch {
    return null;
  }
}

async function loadSamples(): Promise<void> {
  if (loading || !ctx) return;
  loading = true;
  await Promise.all(
    (Object.keys(SAMPLES) as SampleId[]).map(async (id) => {
      try {
        const res = await fetch(`${BASE}/${SAMPLES[id]}`);
        if (!res.ok) throw new Error(String(res.status));
        buffers.set(id, await ctx!.decodeAudioData(await res.arrayBuffer()));
      } catch {
        // Left absent on purpose; callers fall back to the synth.
      }
    }),
  );
  startAmbience();
}

/** Resume audio after a user gesture (browsers require this) and load samples. */
export function unlockAudio(): void {
  const a = ensureCtx();
  if (!a) return;
  if (a.ctx.state === 'suspended') void a.ctx.resume();
  void loadSamples();
}

function playSample(id: SampleId, gain = 1, rate = 1): boolean {
  const buf = buffers.get(id);
  if (!buf || !ctx || !sfxBus) return false;
  const src = ctx.createBufferSource();
  src.buffer = buf;
  src.playbackRate.value = rate;
  const g = ctx.createGain();
  g.gain.value = gain;
  src.connect(g).connect(sfxBus);
  src.start();
  return true;
}

// ---------------------------------------------------------------------------
// Ambience
// ---------------------------------------------------------------------------

let ambienceTimer: number | null = null;

/**
 * Loop the ambience bed with a crossfade.
 *
 * `AudioBufferSourceNode.loop` restarts the buffer instantly at its end, and no
 * generated clip begins and ends at the same amplitude — so native looping puts
 * an audible click into the mix every twenty seconds, which is worse than
 * having no ambience at all. Two overlapping sources with an equal-power
 * crossfade hide the seam entirely.
 */
function startAmbience(): void {
  const buf = buffers.get('ambience');
  if (!buf || !ctx || !ambienceBus || ambienceTimer !== null) return;

  const FADE = 2.5;
  const period = Math.max(1, buf.duration - FADE);

  const schedule = (at: number): void => {
    const src = ctx!.createBufferSource();
    src.buffer = buf;
    const g = ctx!.createGain();
    // Equal-power in and out, so the summed loudness stays flat through the
    // overlap instead of dipping in the middle.
    g.gain.setValueAtTime(0.0001, at);
    g.gain.exponentialRampToValueAtTime(1, at + FADE);
    g.gain.setValueAtTime(1, at + buf.duration - FADE);
    g.gain.exponentialRampToValueAtTime(0.0001, at + buf.duration);
    src.connect(g).connect(ambienceBus!);
    src.start(at);
    src.stop(at + buf.duration + 0.1);
  };

  let next = ctx.currentTime + 0.05;
  schedule(next);
  next += period;

  // Keep one clip queued ahead. Scheduling the whole run up front would pin
  // every source node in memory for as long as the tab is open.
  ambienceTimer = window.setInterval(() => {
    if (!ctx) return;
    while (next < ctx.currentTime + period) {
      schedule(next);
      next += period;
    }
  }, 1000);

  ambienceBus.gain.setTargetAtTime(0.35, ctx.currentTime, 2);
}

/** Duck the bed when the game is not being played. */
export function setAmbienceActive(active: boolean): void {
  if (!ctx || !ambienceBus) return;
  ambienceBus.gain.setTargetAtTime(active ? 0.35 : 0.12, ctx.currentTime, 0.6);
}

// ---------------------------------------------------------------------------
// One-shots
// ---------------------------------------------------------------------------

export function playJump(): void {
  const a = ensureCtx();
  if (!a) return;
  if (playSample('jump', 0.5, 0.95 + Math.random() * 0.1)) return;
  synthJump(a);
}

export function playLand(intensity = 1): void {
  const a = ensureCtx();
  if (!a) return;
  if (playSample('land', Math.min(0.9, 0.35 * intensity), 0.92 + Math.random() * 0.16)) return;
  synthLand(a, intensity);
}

export function playCrumble(): void {
  const a = ensureCtx();
  if (!a) return;
  playSample('crumble', 0.55, 0.9 + Math.random() * 0.2);
}

export function playBounce(): void {
  const a = ensureCtx();
  if (!a) return;
  if (playSample('bounce', 0.6, 0.9 + Math.random() * 0.2)) return;
  synthJump(a);
}

/**
 * Footsteps, driven by distance travelled rather than by a timer.
 *
 * A fixed interval desynchronises from the legs the moment the player changes
 * speed — sprinting produces the same step rate as walking, which reads as the
 * character skating. Accumulating ground distance and firing every stride keeps
 * the cadence tied to how fast they are actually moving.
 */
const STRIDE = 2.1;
let strideAccum = 0;
let lastStep = 0;

export function updateFootsteps(speed: number, grounded: boolean, dt: number): void {
  if (!grounded || speed < 0.6) {
    // Bleed the accumulator so stopping and starting does not fire instantly.
    strideAccum = Math.min(strideAccum, STRIDE * 0.5);
    return;
  }
  strideAccum += speed * dt;
  if (strideAccum < STRIDE) return;
  strideAccum = 0;
  const variants: SampleId[] = ['step_a', 'step_b', 'step_c'];
  // Never the same clip twice running: repetition is what makes footsteps
  // sound like a sound effect rather than like walking.
  let pick = Math.floor(Math.random() * variants.length);
  if (pick === lastStep) pick = (pick + 1) % variants.length;
  lastStep = pick;
  playSample(variants[pick], 0.22 + Math.random() * 0.08, 0.9 + Math.random() * 0.25);
}

export function playWindBurst(): void {
  const a = ensureCtx();
  if (!a) return;
  const t = a.ctx.currentTime;
  const dur = 0.5;
  const buf = a.ctx.createBuffer(1, Math.floor(a.ctx.sampleRate * dur), a.ctx.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < data.length; i++) {
    const e =
      i < data.length * 0.2
        ? i / (data.length * 0.2)
        : 1 - (i - data.length * 0.2) / (data.length * 0.8);
    data[i] = (Math.random() * 2 - 1) * e;
  }
  const src = a.ctx.createBufferSource();
  src.buffer = buf;
  const bp = a.ctx.createBiquadFilter();
  bp.type = 'bandpass';
  bp.frequency.value = 800;
  bp.Q.value = 0.7;
  const g = a.ctx.createGain();
  g.gain.value = 0.18;
  src.connect(bp).connect(g).connect(a.master);
  src.start(t);
}

// ---------------------------------------------------------------------------
// Synth fallbacks, from before the samples existed.
// ---------------------------------------------------------------------------

function synthJump(a: { ctx: AudioContext; master: GainNode }): void {
  const t = a.ctx.currentTime;
  const osc = a.ctx.createOscillator();
  const g = a.ctx.createGain();
  osc.type = 'square';
  osc.frequency.setValueAtTime(220, t);
  osc.frequency.exponentialRampToValueAtTime(520, t + 0.08);
  g.gain.setValueAtTime(0.0001, t);
  g.gain.exponentialRampToValueAtTime(0.18, t + 0.005);
  g.gain.exponentialRampToValueAtTime(0.0001, t + 0.16);
  osc.connect(g).connect(a.master);
  osc.start(t);
  osc.stop(t + 0.2);
}

function synthLand(a: { ctx: AudioContext; master: GainNode }, intensity: number): void {
  const t = a.ctx.currentTime;
  const dur = 0.25;
  const buf = a.ctx.createBuffer(1, Math.floor(a.ctx.sampleRate * dur), a.ctx.sampleRate);
  const data = buf.getChannelData(0);
  for (let i = 0; i < data.length; i++) {
    const e = 1 - i / data.length;
    data[i] = (Math.random() * 2 - 1) * e * e;
  }
  const src = a.ctx.createBufferSource();
  src.buffer = buf;
  const lp = a.ctx.createBiquadFilter();
  lp.type = 'lowpass';
  lp.frequency.value = 320 + intensity * 200;
  const g = a.ctx.createGain();
  g.gain.value = Math.min(0.35, 0.12 * intensity);
  src.connect(lp).connect(g).connect(a.master);
  src.start(t);
}
