#!/usr/bin/env node
/**
 * Generate the game's audio with fal.
 *
 *   node scripts/gen-audio.mjs
 *   node scripts/gen-audio.mjs --only=ambience_jungle --force
 *
 * What is being replaced: audio/sfx.ts is a tiny WebAudio synth — a square-wave
 * blip for the jump, filtered noise for landing. It is fine, and it is also
 * from a different game. A square wave in a photorealistic rainforest is the
 * audio equivalent of an untextured box, and there is no ambience at all, which
 * is the larger problem: silence reads as "unfinished" faster than any visual
 * shortcoming.
 *
 * Ambience is generated long and looped with a crossfade at runtime, because no
 * generator produces a seamless loop and a click every twenty seconds is worse
 * than no ambience.
 */

import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { run } from './fal.mjs';

const OUT_DIR = 'public/assets/audio';
const EST_COST_EACH = 0.04;

const SOUNDS = [
  {
    name: 'ambience_jungle',
    seconds: 22,
    prompt:
      'Dense tropical rainforest ambience, continuous layered insect chorus and cicadas, distant unseen birds calling, faint wind moving through wet leaves high above. No music, no melody, no human voices, no sudden events.',
  },
  {
    name: 'step_stone_a',
    seconds: 1,
    prompt: 'A single soft footstep on damp mossy stone, close, dull and muted, no reverb tail',
  },
  {
    name: 'step_stone_b',
    seconds: 1,
    prompt: 'A single footstep scuffing on wet gritty concrete, close, short and dry',
  },
  {
    name: 'step_stone_c',
    seconds: 1,
    prompt: 'A single footstep on loose rubble and small stones, close, short crunch',
  },
  {
    name: 'jump_effort',
    seconds: 1,
    prompt: 'A short scuff of a shoe pushing off wet stone as someone leaps, dry and close',
  },
  {
    name: 'land_thud',
    seconds: 1,
    prompt:
      'A heavy body landing hard on damp stone, dull low thud with a brief gritty scrape, no music',
  },
  {
    name: 'crumble_crack',
    seconds: 2,
    prompt:
      'Concrete cracking and giving way, sharp initial snap then crumbling grit and small falling debris, dry and close',
  },
  {
    name: 'bounce_spring',
    seconds: 1,
    prompt:
      'A tensioned metal cable or old spring released with a deep resonant twang, launching something upward, wet and rusty',
  },
];

/**
 * fal exposes several text-to-audio families and they take different inputs.
 * Tried in order; the first that returns audio wins.
 */
const GENERATORS = [
  {
    // Note the /v2. The unversioned `fal-ai/elevenlabs/sound-effects` endpoint
    // still exists and still accepts the request — it validates the schema and
    // then fails 400 upstream with:
    //
    //   invalid_model_id: eleven_text_to_sound_v0
    //   Expected one of: ['eleven_text_to_sound_v2']
    //
    // fal's wrapper is pinned to a model ElevenLabs has retired, and passing
    // model_id or model in the input does not override it. The versioned path
    // is the working one. It also returns mp3 rather than WAV, which matters:
    // stable-audio's 22-second ambience came back as a 3.8MB uncompressed WAV.
    model: 'fal-ai/elevenlabs/sound-effects/v2',
    input: (s) => ({ text: s.prompt, duration_seconds: s.seconds }),
  },
  {
    model: 'fal-ai/stable-audio',
    input: (s) => ({ prompt: s.prompt, seconds_total: s.seconds }),
  },
];

function audioUrl(result) {
  return (
    result?.audio?.url ??
    result?.audio_file?.url ??
    result?.audio_url ??
    (typeof result?.audio === 'string' ? result.audio : null) ??
    (Array.isArray(result?.audios) ? result.audios[0]?.url : null) ??
    null
  );
}

/**
 * Try each generator in turn, and say so out loud when one fails.
 *
 * The first version of this swallowed every failure and only reported anything
 * if *all* of them failed. So the ElevenLabs endpoint was 400ing on every
 * single call, the chain quietly fell through to stable-audio, and the run
 * printed a cheerful success line for eight files in a row. The whole audio set
 * was generated by the fallback and nothing in the output said so.
 *
 * A fallback that hides which path it took is not a fallback, it is a way of
 * not finding out. Failures are printed as they happen now, so a degraded run
 * is visibly degraded.
 */
async function generate(sound) {
  const errors = [];
  for (const gen of GENERATORS) {
    try {
      const out = await run(gen.model, gen.input(sound), { timeoutMs: 300_000 });
      const url = audioUrl(out);
      if (url) return { url, model: gen.model };
      errors.push(`${gen.model}: no audio field in ${Object.keys(out).join(',')}`);
    } catch (err) {
      errors.push(`${gen.model}: ${String(err.message).replace(/\s+/g, ' ').slice(0, 300)}`);
    }
    process.stdout.write(`\n         FELL BACK from ${errors.at(-1)}\n         `);
  }
  throw new Error(`no generator succeeded:\n  ${errors.join('\n  ')}`);
}

function extFor(url) {
  const clean = url.split('?')[0].toLowerCase();
  for (const e of ['.mp3', '.wav', '.ogg', '.flac', '.m4a']) if (clean.endsWith(e)) return e;
  return '.mp3';
}

async function main() {
  const force = process.argv.includes('--force');
  const only = process.argv.find((a) => a.startsWith('--only='))?.slice(7).split(',');
  mkdirSync(OUT_DIR, { recursive: true });

  const todo = SOUNDS.filter((s) =>
    only
      ? only.includes(s.name)
      : force || !['.mp3', '.wav', '.ogg'].some((e) => existsSync(`${OUT_DIR}/${s.name}${e}`)),
  );
  if (!todo.length) {
    console.log('[audio] everything already generated; nothing to spend');
    return;
  }
  console.log(
    `[audio] generating ${todo.length}, estimated ~$${(todo.length * EST_COST_EACH).toFixed(2)}`,
  );

  const made = [];
  for (const s of todo) {
    process.stdout.write(`[audio] ${s.name} ... `);
    const { url, model } = await generate(s);
    const res = await fetch(url, { signal: AbortSignal.timeout(180_000) });
    if (!res.ok) throw new Error(`download ${s.name} -> ${res.status}`);
    const buf = Buffer.from(await res.arrayBuffer());
    const file = `${s.name}${extFor(url)}`;
    writeFileSync(`${OUT_DIR}/${file}`, buf);
    console.log(`${(buf.length / 1024).toFixed(0)}kB via ${model.split('/').slice(1).join('/')}`);
    made.push(file);
  }

  writeFileSync(`${OUT_DIR}/manifest.json`, `${JSON.stringify({ files: made }, null, 1)}\n`);
  console.log(`[audio] ${made.length} written to ${OUT_DIR}`);
}

main().catch((err) => {
  console.error(String(err.message));
  process.exitCode = 1;
});
